import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import Appointments from "./../components/pages/Appointments"
export default function Terminkalendar() {
  return (
    <>
      <Head>
        <title>HestiaMed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appointments />
    </>
  );
}
