import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import Patient from "@/components/pages/patient";
import Appointments from "@/components/pages/appointments";
import Statistics from "@/components/pages/statistics";
import Settings from "@/components/pages/settings";
export default function Einstellungen() {
  return (
    <>
      <Head>
        <title>HestiaMed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings />
    </>
  );
}
