
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import Patient from "./../../components/pages/patient";

export default function Patientenverwaltung() {
  return (
    <>
      <Head>
        <title>HestiaMed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Patient />
    </>
  );
}
