<<<<<<< HEAD
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import Patient from "./../../components/pages/patient";

export default function Patientenverwaltung() {
  return (
    <>
      <Head>
        <title>HestiaMed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Patient />
    </>
  );
}
=======
version https://git-lfs.github.com/spec/v1
oid sha256:c9cf26f71ea5ab28f2fef4b7c98fa08438d10c1834c3a8196009507e9c46127d
size 539
>>>>>>> 27aa36463c4f1ad2a7c8c8bc2ccada08a4bca70a
